GET http://[::1]:3333/tasks HTTP/1.1

###

POST http://[::1]:3333/tasks HTTP/1.1
content-type: application/json

{
    "Title":"Comprar Pao",
    "Description":"Devo comprar Agua no mercado amanhã de manhã"
}

###
PUT http://[::1]:3333/tasks/7792be97-0a1e-4c8c-b8fb-e879681fb010 HTTP/1.1
content-type: application/json

{
    "Title":"Comprar Comida"
}
###

DELETE http://[::1]:3333/tasks/8b45a9f5-ab94-4e28-8952-86f45f378cba HTTP/1.1